excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

analyzer_rules:
  - explicit_self

disabled_rules:
  - todo
  - multiline_arguments_brackets
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - trailing_closure
  - conditional_returns_on_newline

opt_in_rules:
  - empty_count
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - inclusive_language
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 1000
  error: 2500
force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
function_body_length:
  warning: 40
  error: 300
implicitly_unwrapped_optional:
  severity: error
line_length: 250
type_body_length:
  warning: 300
  error: 400
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]
large_tuple:
  warning: 3
  error: 5
conditional_returns_on_newline:
    if_only: true
trailing_whitespace:
    ignores_empty_lines: true
identifier_name:
  min_length:
    warning: 3
    error: 1
  excluded:
    - ar
    - id
    - URL
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - i
    - a4
reporter: "xcode"
