import "./../Submodules/WeTransfer-iOS-CI/Fastlane/Fastfile"

desc "Run the tests and prepare for Danger"
lane :test do |options|
  test_project(
    project_path: "../",
    project_name: "AirHUD",
    scheme: "AirHUD")
end

