import "./../Submodules/WeTransfer-iOS-CI/Fastlane/Fastfile"

desc "Run the tests and prepare for Danger"
lane :test do |options|
  test_package(
        package_name: 'AirHUD',
        package_path: './',
        scheme: "AirHUD")
end